services:
  daily-status:
    profiles:
      - jobs
    build:
      context: .
    image: daily-status:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
      - INFISICAL_ENV=${INFISICAL_ENV:-dev}
      - INFISICAL_PATH=${INFISICAL_PATH:-/}
      - INFISICAL_API_URL=${INFISICAL_API_URL:-http://host.docker.internal:8085/api}
      - INFISICAL_DISABLE_UPDATE_CHECK=true
      - GITHUB_ORG=${GITHUB_ORG:-ThriveMarket}
      - SLACK_THREAD_KEYWORD=${SLACK_THREAD_KEYWORD:-Daily Status Updates}
      - LOOKBACK_HOURS=${LOOKBACK_HOURS:-14}
    command: ["--slack"]
    restart: "no"
